spring:
  application:
    name: studydict
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/infodict
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
  security:
    user:
      username: chamdarango
      password: ineastsea
server:
  port: 2230
---
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      username: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
server:
  port: ${SPRING_SERVER_PORT}