spring:
  application:
    name: studydict
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/infodict
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
  security:
    user:
      username: chamdarango
      password: ineastsea
  # Hibernate ??
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 2230
